import {test} from 'node:test';import assert from 'node:assert/strict';import {zipSync,strToU8} from 'fflate';import {importDocument} from './document-import.js';
export function wordFixture(){return zipSync(Object.fromEntries(Object.entries({
 '[Content_Types].xml':'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>',
 '_rels/.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="r1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>',
 'word/document.xml':'<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:t>导入测试标题</w:t></w:r></w:p><w:p><w:r><w:rPr><w:b/></w:rPr><w:t>正文重点</w:t></w:r></w:p></w:body></w:document>'
 }).map(([k,v])=>[k,strToU8(v)])));}
export function pdfFixture(text='PDF import preserves this sentence.'){const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];const stream=`BT /F1 12 Tf 50 700 Td (${text}) Tj ET`;objects.push(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);let out='%PDF-1.4\n',offsets=[0];objects.forEach((v,i)=>{offsets.push(out.length);out+=`${i+1} 0 obj\n${v}\nendobj\n`;});const xref=out.length;out+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(out);}
test('Word imports heading and bold into editable Markdown',async()=>{const v=await importDocument({filename:'test.docx',base64:Buffer.from(wordFixture()).toString('base64')});assert.match(v.markdown,/# 导入测试标题/);assert.match(v.markdown,/\*\*正文重点\*\*/);});
test('PDF imports real page text and flags layout limits',async()=>{const v=await importDocument({filename:'test.pdf',base64:pdfFixture().toString('base64')});assert.match(v.markdown,/PDF import preserves this sentence/);assert.ok(v.warnings.length);});
test('empty scanned PDF is reported and invalid documents rejected',async()=>{await assert.rejects(importDocument({filename:'empty.pdf',base64:pdfFixture('').toString('base64')}),/OCR/);await assert.rejects(importDocument({filename:'old.doc',base64:'YQ=='}),/docx/);await assert.rejects(importDocument({filename:'bad.pdf',base64:'YQ=='}),/PDF/);});
